### PR TITLE
2019 dec instructor training

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by apreshill** [comment]
Hey @gvwilson - the dates suggest this is 2 days, 4 hours each. But the text has both of these "this one-day workshop" and "run 4 hours each day".

**Comment by gvwilson** [comment]
Changes made - lemme know?

**Comment by apreshill** [comment]
lgtm- thanks!

**Comment by apreshill** [comment]
You can see it here:

https://education.rstudio.com/events/

It'll be in a sticky after the Atlanta workshops in October.

**Pull request merged**
