### PR TITLE
intern blog post

### PR DESCRIPTION
**Pull request by MayaGans**
- adding blog post 
- images added to post folder
- thumbnail image
- wide image

### CODE REVIEW

**Comment by apreshill** [comment]
also here is deploy preview: https://deploy-preview-65--rstudio-education.netlify.com/blog/2019/10/my-javascript-internship-at-rstudio/

**Comment by apreshill** [comment]
Hi @MayaGans,

I changed the thumbnail and wide images since they are so small, so you may want to add in the other images or other screenshots as you see fit. Also I noticed that you never link to your own blog with all the blog posts related to the project: https://maya.rbind.io/tidyblocks/

Might be helpful for readers who want to learn more?

Alison

**Comment by apreshill** [comment]
Hey @MayaGans,

Thank you and this is such a fun read! Can you do one last thing- in the YAML is a description key- can you write like 1-2 sentences for that? I put in some placeholder text for now. It ends up being a short snippet on the post listing page.

Thanks! I set the publish date to Monday if that is OK with you-
Alison

**Comment by MayaGans** [comment]
@apreshill -- description added! Let me know if there's anything else I can do

**Comment by gvwilson** [comment]
Shucks, ma'am, you know I blush when you all-caps me...

**Pull request merged**
