### PR TITLE
Blog post for Christian's mentorship reflection

### PR DESCRIPTION
**Pull request by juliasilge**
This is a draft blog post on Christian Okoth's reflection of her mentorship experience from this past fall semeseter.

### CODE REVIEW

**Comment by juliasilge** [comment]
@cmokoth Here is the draft blog post for you to take look!

There are a couple of ways for you to see the post. The easiest way for you to see the preview is [here](https://deploy-preview-196--rstudio-education.netlify.app/blog/2021/01/ncsu-mentorship-reflect/), or you can click on "Files changed" to see the files I added that create this blog post.

If you have comments on things to change, you can add comments here in this thread, or comment on the files themselves line by line.

I added an image for you to see what it will look like (I chose one from the [WOCinTech](https://unsplash.com/@wocintechchat) collection) but if you find a different image on Unsplash that you would prefer to use, just let me know and we can switch it out.

**Comment by cmokoth** [comment]
This all looks great!!

**Comment by juliasilge** [comment]
Yay! 🥳 Thanks so much @cmokoth.

**Comment by juliasilge** [comment]
@apreshill This blog post is now ready to go! 🚀  

The dates will need to be updated to whatever you would want for publication.

**Comment by apreshill** [comment]
Thanks! I'll merge in Wednesday Feb 17 ❤️

**Comment by apreshill** [comment]
Heads up- will be merging in tomorrow AM!

**Pull request merged**
