### PR TITLE
Blog post about RStudio Internships 2020

### PR DESCRIPTION
**Pull request by gvwilson**
cc @dfalty

### CODE REVIEW

**Comment by dfalty** [comment]
```
Successful candidates will be familiar with test automation and have some experience with R
```
I think we might want to put `R and Python` here. Our test automation is written mostly in Python so it will be hard to have a candidate not familiar with Python.

```
familiarity with the Unix shell, Python, and/or JavaScript will be an asset as well.
```
I think we can take these three out if we mention Python above. We could replace it with Selenium, Docker, Vagrant, cloud platforms (aws, azure, google cloud), terraform, ansible, testthat, CI (Jenkins). Is that too much to add? Our test infrastructure uses these technologies so all of them are applicable. 

```
To demonstrate these skills and your ability to work with Git and GitHub, your application needs to include a link to a package, Shiny app, or data analysis repository on GitHub. 
```
 package, Shiny app, or data analysis repository isn't as applicable for QA. Maybe `link to test scripts or test plan on GitHub`?

I'm wondering if that's too vague. Working selenium tests would be wonderful to see. We used to have a take-home assignment for QA candidates where we had them create a test plan and automate a portion of it with their tools of choice. Do you think it would be worth it to have a suggested idea for a project if they don't have one to share? It could be as simple as "create some UI automated tests against rstudio.cloud with your tools of choice".

**Comment by gvwilson** [comment]
Thanks @dfalty - comments incorporated. Please let us know if this looks good and we'll get it out. cc @apreshill

**Comment by dfalty** [comment]
LGTM!

**Comment by apreshill** [comment]
Thanks @gvwilson & @dfalty!

**Pull request merged**
