### PR TITLE
Add ymlthis post

### PR DESCRIPTION
**Pull request by malcolmbarrett**

### CODE REVIEW

**Comment by apreshill** [comment]
Hi @malcolmbarrett -

This is awesome! For some reason, my blog post archetypes aren't populating in the new post add-in, so I made some changes and added some additional YAML (haha, oh the irony) parameters- can you include a link and attribution to the thumbnail/banner stones photo and a brief description (shows up on the post listing page)? I also made the knitr default comment character nothing instead of 2 hashtags- let me know what you think...

Alison

**Comment by malcolmbarrett** [comment]
Oh, I've had that issue, too. A bug in the add-in?

Anyway, I updated the post with those items!

**Comment by apreshill** [comment]
Ah thank you for saying you've noticed it too! I need to file an issue on the blogdown repo- the archetypes are found when I use Hugo from the command line, but I can't tell if it is some kind of error with Hugo, blogdown, page bundles, ugh. But I spent all this time making lovely helpful archetypes and no one sees them :(

Thanks for the updates! I'll merge in in a few.

**Comment by malcolmbarrett** [comment]
After a little experimenting, I think it might be because of page bundles. I'm not sure, but I think the issue is here https://github.com/rstudio/blogdown/blob/b5e310d7e33c3e35c56120dd2af486f145866c98/R/hugo.R#L243

**Pull request merged**
