### PR TITLE
Carl r markdown workshop

### PR DESCRIPTION
**Pull request by cdhowe**
Here's my crosstalk tutorial blog posting for Yihui's and my R Markdown workshop. See what you think. My Netlify preview link isn't updating, so let me know if it doesn't render the HTML widgets or if you see other weirdnesses. The blog post is now a .Rmd file instead of .Rmarkdown.

### CODE REVIEW

**Comment by sarahemlin** [comment]
Hey Carl!  

Thank you for the post!  Action items for you are 1) fix the typo in the first sentence ('s), 2) remove output: html_document, because blogdown's output format is default and your text overwrites it, and 3) it looks like you have duplicate code chunks throughout your post with the only difference being either echo=false or eval=false--are they supposed to be like that?  

We're still not getting your html widgets to render, so Alison is going to figure that out.  It appears the the widgets are inserting CSS code and breaking her CSS for the site--fonts and font colors are off in addition to the widgets not rendering.

--Sarah

**Comment by cdhowe** [comment]
Will fix those things and resubmit. I do have duplicate code chunks because I want to suppress the warning messages that are emitted by those code chunks without making the code adding suppresswarning functions that would make it look more ugly (in particular, the leaflet package always seems to generate a message that talks about its lat and lng assignments).

Re HTML widgets not rendering, that seems odd, but I defer to our blogdown expert on what is happening there. Seems to me like it should work -- it's just HTML and Javascript, and I would not expect naming collisions....

-C

**Comment by cdhowe** [comment]
Netlify preview is still using an old version. The version I pushed's first heading is "`Crosstalk`: the quick summary" not "The TL;DR Quick Summary".

**Comment by apreshill** [comment]
Hi @cdhowe,

Not everything in `static/` can be deleted and regenerated. All the site images and fonts for example were in there. You can see the deploy preview here:

https://deploy-preview-102--rstudio-education.netlify.com/

We'll either need to restore the these changes before merging in, or start a new branch/PR with only the post itself in there. I think I have a close-to-working solution for showing html widgets in a post here.

**Pull request closed without merging**
