### PR TITLE
r for excel blog .md

### PR DESCRIPTION
**Pull request by jules32**
Hi @apreshill ! Here is the blog post, please feel free to edit; I know the tl;dr stuff at the top is a bit messed up and there is some yaml differences for the rstudio blog vs openscapes blog.  I'll upload the photos next :)

### CODE REVIEW

**Comment by jules32** [comment]
Hmm I guess I don't know how to upload additional files (.pngs) to this pull request. Sorry. They are in <https://github.com/Openscapes/website/tree/master/static/img/blog> and I've also pasted them below. I'm also happy to upload them myself if you show me how :)

tweet-juliesquid-r-for-excel
horst-esm-workflow
r-for-excel-monsters-square

r-for-excel-instructors

r-for-excel-monsters

**Comment by apreshill** [comment]
@jules32 @allisonhorst

Here is the deploy preview:
https://deploy-preview-97--rstudio-education.netlify.com/blog/2020/02/conf20-r-excel/

LMK if all looks good to you :)

**Comment by jules32** [comment]
Hi! Looks great to me! 

This is minor but now that I'm looking at it today, we have Allison's cool Raw data -> workflow twice...could we swap out the first image (horst-esm-workflow.png) with this one? 
horst-r-excel-disco

Thanks! I'll post on Openscapes so that the link is live :)

**Comment by jules32** [comment]
Aah and a few tiny editorial fixes (sorry) – 

1. could you add the words in bold: " a newcomer we **felt was** time well spent"
2. remove the errant `)` after "backronym"

Thanks @apreshill !

**Comment by apreshill** [comment]
Got it. I struggled to find a good photo for the thumbnail and upper banner. If you can find a better one, please let me know!

https://unsplash.com/

**Pull request merged**
