### PR TITLE
Julia's blog post on interactive courses

### PR DESCRIPTION
**Pull request by juliasilge**
Here is the draft of my blog post on creating interactive courses.

This needs feedback/approval from @flor14 and @noamross.

### CODE REVIEW

**Comment by juliasilge** [comment]
You can check out the [preview blog post here](https://deploy-preview-133--rstudio-education.netlify.app/blog/2020/05/teach-interactive-course/) and leave feedback either as a review/comment on the `.Rmarkdown` file itself or just here.

**Comment by noamross** [comment]
L Great TM!

**Comment by apreshill** [comment]
Note to myself: publish date is Wednesday 2020/05/27

**Comment by juliasilge** [comment]
I just picked that date randomly FYI and am flexible.

**Comment by juliasilge** [comment]
I integrated a bit of feedback from @flor14 and this is now ready for any edits from you, @apreshill!

**Comment by apreshill** [comment]
Thanks all! We are live 🤝

**Pull request merged**
