### PR TITLE
Conf workshops blog post for @mine-cetinkaya-rundel

### PR DESCRIPTION
**Pull request by apreshill**
for you 😸

### CODE REVIEW

**Comment by apreshill** [comment]
You can use the branch deploy or the deploy preview for this PR from Netlify:

PR:
https://deploy-preview-71--rstudio-education.netlify.com/

Branch:
https://conf-workshops-mine--rstudio-education.netlify.com/

**Comment by mine-cetinkaya-rundel** [comment]
@apreshill I couldn't add you as a reviewer for some reason, but the post is ready.

I wish the flexdashboard I made had blue colors matching the RStudio blue, but I was having a hard time with tweaking the css and decided to leave it.

**Comment by apreshill** [comment]
Awesome- thanks- I'll plan to publish tomorrow. I responded re: CSS on Slack.

**Comment by apreshill** [comment]
@mine-cetinkaya-rundel do you think we should note somewhere which workshops (like time series) are sold out?

**Comment by mine-cetinkaya-rundel** [comment]
I thought about that, but then decided that would mean updating at least the app periodically, and I worried I might not do it regularly enough for it to be useful. I think that information is updated on cvent regularly so I thought that's good enough?

**Pull request merged**
