### PR TITLE
Blog post sharing past instructor certification exams

### PR DESCRIPTION
**Pull request by gvwilson**
Haven't built locally to preview.

### CODE REVIEW

**Comment by apreshill** [comment]
Hi @gvwilson - can you move the external Rmd file (and all of its dependencies) to a new folder in `static/`? The output format isn't something `blogdown` can render. I can fix the build then on my side- I just can't tell what dependency files the blog post needs versus the `.Rmd`

**Comment by gvwilson** [comment]
Sure - what syntax do I use to link to that file under `static`? I.e., what's the equivalent of Jekyll's `site.url` variable (that gives me the root of the deployed project)?

**Comment by apreshill** [comment]
I don't know- I would just manually move to a folder like `static/blog-instructor...{rest of slug here}`. I just need blogdown to not try to render that output format.

**Comment by gvwilson** [comment]
Right, but when I insert the link into my RMarkdown, do I use `http://education.rstudio.com/static/whatever/whatever.Rmd` (i.e., put the absolute URL in my blog post) or `../../../../../../../../wait-for-it/../../static/whatever/whatever.Rmd` or...? What's the Hugo/Blogdown convention?

**Comment by apreshill** [comment]
Oh I get what you are asking (sorry, the Jekyll bit confused me!). To do a relative link to that directory, try `/folder_inside_static/etc/etc`. You don't need to name static in your relative link as it is assumed (I think- not tested with current borked up site theme).

**Comment by gvwilson** [comment]
[small voice] If I put the .csv and .Rmd files from the exam in a .zip and put that in the blog post directory and link to that will that work because I'm 99% sure the `/absolute-path/approach` will wind up looking under - you know what? I'm not sure of anything at this point. Zip. Zilch. Zero.

**Comment by apreshill** [comment]
@gvwilson can you fix my final plot? I gave it the good ol' college try to reproduce it 😭 Otherwise, I think this should render fine now

**Pull request merged**
