### PR TITLE
draft cheatsheets post

### PR DESCRIPTION
**Pull request by apreshill**
Hi @garrettgman,

Here is a branch to edit- you can see the deploy preview through netlify every time you serve site and push. I think it reads pretty well, but if you get a moment, a short description and maybe a bit of an intro at the top I think would be great.

Thanks!
Alison

### CODE REVIEW

**Comment by sarahemlin** [comment]
Hi @garrettgman !  Would you be able to review & edit this blog post please?  I'll merge once it's ready.  Thank you!

**Comment by garrettgman** [comment]
I've added an intro and reviewed the post. Please let me know if this suffices, and thanks!

**Comment by sarahemlin** [comment]
Thanks, @garrettgman!  My thoughts: the beginning was kind of abrupt--who is this aimed at?  I was also a bit confused until I got further into the post that non-employees would be making RStudio cheatsheets.  Then I figured out we accept others adding additions for other packages/topics into our repository.
If I could, I'd like to add to the pick a color guidelines a suggestion that they use a color that speaks to the package hex sticker (if it's a package cheatsheet).  It's a visual cue that lowers the cognitive load and helps readers match information on the same topic.

**Comment by garrettgman** [comment]
@sarahemlin if you make the changes you suggest, I'd be happy to review them.

**Comment by apreshill** [comment]
@sarahemlin can you serve site and update the .md file so the deploy preview updates? I think the .Rmarkdown file was edited but the .md file was not. Also the post date needs to be updated as it is old (03/02/2020). Thanks all!

**Comment by garrettgman** [comment]
@apreshill your hunch is correct. I am unfamiliar with the process here, so I edited only the .Rmd. I figured that would propagate manually.

**Comment by sarahemlin** [comment]
@apreshill , I think this is ready to go.  Please confirm!

**Pull request merged**
